# Configuração LLM de Produção - DataHawk v2.0
# Sistema Multi-Modelo Otimizado com Seleção Inteligente

llm:
  # Servidor de produção
  server:
    url: "http://localhost:8000"
    health_check_interval: 30 # segundos
    timeout: 15 # segundos aumentado
    max_retries: 3
    fallback_enabled: true

  # Auto-seleção baseada em recursos disponíveis
  auto_selection:
    enabled: true
    memory_threshold_gb: 0.5 # Margem de segurança
    prefer_quality: false # Se true, prefere modelos maiores
    fallback_order: ["tinyllama", "qwen-1.8b", "gemma-2b", "phi3-mini"]

  # Modelos suportados (em ordem de capacidade)
  models:
    - name: "tinyllama"
      path: "models/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"
      memory_gb: 1.5
      description: "Ultra rápido, baixo consumo - Ideal para testes e ambientes limitados"
      strengths: ["speed", "low_memory"]
      optimal_for: ["simple_validation", "quick_comparisons"]
      context_size: 1024
      threads: 2
      batch_size: 64
      temperature: 0.2

    - name: "qwen-1.8b"
      path: "models/qwen1.5-1.8b-chat.Q4_K_M.gguf"
      memory_gb: 2.0
      description: "Bom para raciocínio numérico e lógica - CPF, CNPJ, números"
      strengths: ["numerical_reasoning", "logical_thinking"]
      optimal_for: ["number_validation", "cpf_cnpj", "financial_data"]
      context_size: 2048
      threads: 2
      batch_size: 128
      temperature: 0.1

    - name: "gemma-2b"
      path: "models/gemma-2b-it.Q4_K_M.gguf"
      memory_gb: 2.5
      description: "Equilibrado, excelente PT-BR - Nomes, endereços, texto em português"
      strengths: ["portuguese", "text_understanding", "cultural_context"]
      optimal_for: ["name_validation", "address_validation", "portuguese_text"]
      context_size: 2048
      threads: 3
      batch_size: 128
      temperature: 0.1

    - name: "phi3-mini"
      path: "models/phi-3-mini-4k-instruct.Q4_K_M.gguf"
      memory_gb: 3.5
      description: "Qualidade superior geral - Melhor para casos complexos"
      strengths: ["general_intelligence", "complex_reasoning", "accuracy"]
      optimal_for: ["complex_validation", "mixed_content", "fallback"]
      context_size: 4096
      threads: 3
      batch_size: 128
      temperature: 0.1

  # Configurações otimizadas por cenário
  field_type_mapping:
    # Campos numéricos -> Qwen
    number: "qwen-1.8b"
    cpf: "qwen-1.8b"
    cnpj: "qwen-1.8b"
    currency: "qwen-1.8b"
    percentage: "qwen-1.8b"

    # Campos de texto português -> Gemma
    name: "gemma-2b"
    address: "gemma-2b"
    city: "gemma-2b"
    description: "gemma-2b"

    # Campos simples -> TinyLlama
    id: "tinyllama"
    code: "tinyllama"
    category: "tinyllama"

    # Campos complexos -> Phi-3
    email: "phi3-mini"
    phone: "phi3-mini"
    mixed: "phi3-mini"
    complex: "phi3-mini"

  # Sistema de aprendizado retroativo
  learning:
    enabled: true
    store_decisions: true
    confidence_threshold: 0.7 # Apenas decisões com alta confiança
    feedback_loop: true
    pattern_detection: true
    model_adaptation: true

    # Métricas para melhoria contínua
    metrics:
      track_accuracy: true
      track_performance: true
      track_field_types: true
      track_model_selection: true

    # Cache inteligente baseado em padrões
    intelligent_cache:
      enabled: true
      similarity_threshold: 0.95
      max_entries: 10000
      ttl_hours: 168 # 7 dias

  # Configurações de validação específica
  validation:
    enable_fallback: true
    confidence_threshold: 0.7
    max_prompt_length: 300 # Aumentado para modelos maiores
    simple_prompts: true # Para modelos pequenos
    adaptive_prompts: true # Adapta prompt ao modelo

    # Estratégia de ensemble (múltiplos modelos)
    ensemble:
      enabled: false # Desabilitado por padrão para economia
      min_models: 2
      max_models: 3
      voting_strategy: "weighted" # weighted, majority, best_confidence

  # Monitoramento e observabilidade
  monitoring:
    track_model_performance: true
    track_memory_usage: true
    track_response_times: true
    alert_on_degradation: true

    # Logs estruturados
    logging:
      level: "info"
      include_decisions: true
      include_reasoning: true
      include_metrics: true
