targetUrl: 'https://www.gov.br/pt-br/servicos/{serviceCode}'
fieldMappings:
  - csvField: 'serviceName'
    webSelector: 'h1'
    fieldType: 'text'
    required: true
    validationStrategy: 'dom_extraction'
  - csvField: 'serviceDescription'
    webSelector: '.description, .summary, .lead'
    fieldType: 'text'
    required: true
    validationStrategy: 'dom_extraction'
  - csvField: 'serviceCategory'
    webSelector: '.category, .breadcrumb, .tag'
    fieldType: 'text'
    required: false
    validationStrategy: 'dom_extraction'
  - csvField: 'audience'
    webSelector: '.audience, .target, .publico'
    fieldType: 'text'
    required: false
    validationStrategy: 'dom_extraction'
  - csvField: 'departmentResponsible'
    webSelector: '.orgao, .responsavel, .ministerio'
    fieldType: 'text'
    required: false
    validationStrategy: 'dom_extraction'

validationRules:
  confidence:
    minimumOverall: 0.7
    minimumField: 0.6
    ocrThreshold: 0.6
    fuzzyMatchThreshold: 0.8
  fuzzyMatching:
    enabled: true
    algorithms: ['levenshtein', 'jaro_winkler']
    stringSimilarityThreshold: 0.75
    caseInsensitive: true
    ignoreWhitespace: true
  errorHandling:
    maxRetryAttempts: 3
    retryDelayMs: 2000
    exponentialBackoff: true
    criticalErrors: ['navigation_timeout', 'page_not_found']
    recoverableErrors: ['element_not_found', 'ocr_low_confidence']
    escalationThreshold: 0.2

performance:
  batchProcessing: true
  batchSize: 3
  parallelWorkers: 1
  caching:
    domSnapshots: true
    ocrResults: true
    validationDecisions: false
    ttl: 3600
  timeouts:
    navigation: 60000 # Aumentado para sites gov.br
    domExtraction: 30000
    ocrProcessing: 45000
    validationDecision: 30000
    evidenceCollection: 30000

evidence:
  retentionDays: 30
  screenshotEnabled: true
  domSnapshotEnabled: true
  compressionEnabled: true
  includeInReports: true
