target_url: https://www.gov.br/pt-br/servicos/{serviceCode}
field_mappings:
  - csv_field: serviceName
    web_selector: h1
    field_type: text
    required: true
    validation_strategy: dom_extraction
  - csv_field: serviceDescription
    web_selector: .description, .summary, .lead
    field_type: text
    required: true
    validation_strategy: dom_extraction
  - csv_field: serviceCategory
    web_selector: .category, .breadcrumb, .tag
    field_type: text
    required: false
    validation_strategy: dom_extraction
  - csv_field: audience
    web_selector: .audience, .target, .publico
    field_type: text
    required: false
    validation_strategy: dom_extraction
  - csv_field: departmentResponsible
    web_selector: .orgao, .responsavel, .ministerio
    field_type: text
    required: false
    validation_strategy: dom_extraction
validation_rules:
  confidence:
    minimum_overall: 0.7
    minimum_field: 0.6
    ocr_threshold: 0.6
    fuzzy_match_threshold: 0.8
  fuzzy_matching:
    enabled: true
    algorithms:
      - levenshtein
      - jaro_winkler
    string_similarity_threshold: 0.75
    case_insensitive: true
    ignore_whitespace: true
  error_handling:
    max_retry_attempts: 3
    retry_delay_ms: 2000
    exponential_backoff: true
    critical_errors:
      - navigation_timeout
      - page_not_found
    recoverable_errors:
      - element_not_found
      - ocr_low_confidence
    escalation_threshold: 0.2
performance:
  batch_processing: true
  batch_size: 3
  parallel_workers: 1
  caching:
    dom_snapshots: true
    ocr_results: true
    validation_decisions: false
    ttl: 3600
  timeouts:
    navigation: 60000
    dom_extraction: 30000
    ocr_processing: 45000
    validation_decision: 30000
    evidence_collection: 30000
evidence:
  retention_days: 30
  screenshot_enabled: true
  dom_snapshot_enabled: true
  compression_enabled: true
  include_in_reports: true
