# Configuração DataHawk v2.0 - Sistema Multi-Modelo
# Demonstra uso otimizado de diferentes modelos por tipo de campo

targetUrl: 'https://httpbin.org/html'

fieldMappings:
  # Campos simples -> TinyLlama (rápido)
  - csvField: 'id'
    webSelector: 'h1'
    fieldType: 'text'
    required: true
    validationStrategy: 'dom_extraction'

  - csvField: 'code'
    webSelector: 'p:first-of-type'
    fieldType: 'text'
    required: false
    validationStrategy: 'dom_extraction'

  # Campos numéricos -> Qwen (raciocínio numérico)
  - csvField: 'cpf'
    webSelector: '.cpf'
    fieldType: 'text'
    required: false
    validationStrategy: 'dom_extraction'

  - csvField: 'salary'
    webSelector: '.salary'
    fieldType: 'currency'
    required: false
    validationStrategy: 'dom_extraction'

  # Campos de texto português -> Gemma (PT-BR)
  - csvField: 'name'
    webSelector: 'h1'
    fieldType: 'name'
    required: true
    validationStrategy: 'dom_extraction'

  - csvField: 'address'
    webSelector: '.address'
    fieldType: 'address'
    required: false
    validationStrategy: 'dom_extraction'

  # Campos complexos -> Phi-3 (qualidade superior)
  - csvField: 'email'
    webSelector: '.email'
    fieldType: 'email'
    required: false
    validationStrategy: 'dom_extraction'

validationRules:
  confidence:
    minimumOverall: 0.7
    minimumField: 0.6
    ocrThreshold: 0.6
    fuzzyMatchThreshold: 0.8
  fuzzyMatching:
    enabled: true
    algorithms: ['levenshtein', 'jaro_winkler']
    stringSimilarityThreshold: 0.8
    numberTolerance: 0.001
    caseInsensitive: true
    ignoreWhitespace: true
  normalization:
    whitespace:
      trimLeading: true
      trimTrailing: true
      normalizeInternal: true
    case:
      email: 'lowercase'
      name: 'title_case'
      text: 'preserve'
    specialCharacters:
      removeAccents: true
      normalizeQuotes: true
      normalizeDashes: true
    numbers:
      decimalSeparator: '.'
      thousandSeparator: ','
      currencySymbolRemove: true
    dates:
      targetFormat: 'YYYY-MM-DD'
      inputFormats: ['MM/DD/YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD']
  errorHandling:
    maxRetryAttempts: 3
    retryDelayMs: 2000
    exponentialBackoff: true
    criticalErrors: ['navigation_timeout', 'page_not_found']
    recoverableErrors: ['element_not_found', 'ocr_low_confidence']
    escalationThreshold: 0.1

performance:
  batchProcessing: true
  batchSize: 5
  parallelWorkers: 2
  caching:
    domSnapshots: true
    ocrResults: true
    validationDecisions: true # Habilitado para aproveitar cache inteligente
    ttl: 3600
  timeouts:
    navigation: 30000
    domExtraction: 15000
    ocrProcessing: 45000
    validationDecision: 30000
    evidenceCollection: 10000

evidence:
  retentionDays: 30
  screenshotEnabled: true
  domSnapshotEnabled: true
  compressionEnabled: true
  includeInReports: true
