targetUrl: 'https://pt.wikipedia.org/wiki/{articleName}'
fieldMappings:
  - csvField: 'title'
    webSelector: '#firstHeading'
    fieldType: 'text'
    required: true
    validationStrategy: 'dom_extraction'
  - csvField: 'introduction'
    webSelector: '#mw-content-text .mw-parser-output p:first-of-type'
    fieldType: 'text'
    required: true
    validationStrategy: 'dom_extraction'
  - csvField: 'infoboxTitle'
    webSelector: '.infobox .infobox-title'
    fieldType: 'text'
    required: false
    validationStrategy: 'dom_extraction'
  - csvField: 'lastModified'
    webSelector: '#footer-info-lastmod'
    fieldType: 'text'
    required: false
    validationStrategy: 'dom_extraction'
  - csvField: 'imageCaption'
    webSelector: '.infobox .infobox-image .infobox-caption'
    fieldType: 'text'
    required: false
    validationStrategy: 'dom_extraction'

validationRules:
  confidence:
    minimumOverall: 0.7
    minimumField: 0.6
    ocrThreshold: 0.6
    fuzzyMatchThreshold: 0.8
  fuzzyMatching:
    enabled: true
    algorithms: ['levenshtein', 'jaro_winkler']
    stringSimilarityThreshold: 0.8
    numberTolerance: 0.001
    caseInsensitive: true
    ignoreWhitespace: true
  normalization:
    whitespace:
      trimLeading: true
      trimTrailing: true
      normalizeInternal: true
    case:
      email: 'lowercase'
      name: 'preserve'
      text: 'preserve'
    specialCharacters:
      removeAccents: false
      normalizeQuotes: true
      normalizeDashes: true
    numbers:
      decimalSeparator: '.'
      thousandSeparator: ','
      currencySymbolRemove: true
    dates:
      targetFormat: 'YYYY-MM-DD'
      inputFormats: ['MM/DD/YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD']
  errorHandling:
    maxRetryAttempts: 2
    retryDelayMs: 1000
    exponentialBackoff: true
    criticalErrors: ['navigation_timeout', 'page_not_found']
    recoverableErrors: ['element_not_found', 'ocr_low_confidence']
    escalationThreshold: 0.2

performance:
  batchProcessing: true
  batchSize: 5
  parallelWorkers: 2
  caching:
    domSnapshots: true
    ocrResults: true
    validationDecisions: false
    ttl: 3600
  timeouts:
    navigation: 30000
    domExtraction: 15000
    ocrProcessing: 45000
    validationDecision: 30000
    evidenceCollection: 10000

evidence:
  retentionDays: 30
  screenshotEnabled: true
  domSnapshotEnabled: true
  compressionEnabled: true
  includeInReports: true 