targetUrl: 'https://emojipedia.org/search?q={searchTerm}'
fieldMappings:
  - csvField: 'emojiName'
    webSelector: '.search-results ol li:first-child h2 a'
    fieldType: 'text'
    required: true
    validationStrategy: 'dom_extraction'
  - csvField: 'emojiSymbol'
    webSelector: '.search-results ol li:first-child a.EmojiDetail-header > span.Emoji'
    fieldType: 'text'
    required: true
    validationStrategy: 'dom_extraction'
  - csvField: 'shortDescription'
    webSelector: '.search-results ol li:first-child > a > div.ExtraInfo'
    fieldType: 'text'
    required: false
    validationStrategy: 'dom_extraction'
  - csvField: 'categoryText'
    webSelector: '.search-results ol li:first-child .EmojiDetail-subdescription'
    fieldType: 'text'
    required: false
    validationStrategy: 'dom_extraction'

validationRules:
  confidence:
    minimumOverall: 0.6 # Reduzido para aceitar mais facilmente caracteres especiais
    minimumField: 0.5
    ocrThreshold: 0.5
    fuzzyMatchThreshold: 0.7
  fuzzyMatching:
    enabled: true
    algorithms: ['levenshtein', 'jaro_winkler']
    stringSimilarityThreshold: 0.7
    numberTolerance: 0.001
    caseInsensitive: true
    ignoreWhitespace: true
  normalization:
    whitespace:
      trimLeading: true
      trimTrailing: true
      normalizeInternal: true
    case:
      email: 'lowercase'
      name: 'preserve'
      text: 'preserve'
    specialCharacters:
      removeAccents: false # Importante para preservar acentos
      normalizeQuotes: false # Importante para preservar aspas
      normalizeDashes: false # Importante para preservar traços
    numbers:
      decimalSeparator: '.'
      thousandSeparator: ','
      currencySymbolRemove: true
    dates:
      targetFormat: 'YYYY-MM-DD'
      inputFormats: ['MM/DD/YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD']
  errorHandling:
    maxRetryAttempts: 3
    retryDelayMs: 2000
    exponentialBackoff: true
    criticalErrors: ['navigation_timeout', 'page_not_found']
    recoverableErrors: ['element_not_found', 'ocr_low_confidence']
    escalationThreshold: 0.3

performance:
  batchProcessing: true
  batchSize: 3
  parallelWorkers: 1 # Reduzido para garantir processamento correto
  caching:
    domSnapshots: true
    ocrResults: true
    validationDecisions: false
    ttl: 3600
  timeouts:
    navigation: 30000
    domExtraction: 15000
    ocrProcessing: 45000
    validationDecision: 30000
    evidenceCollection: 10000

evidence:
  retentionDays: 30
  screenshotEnabled: true
  domSnapshotEnabled: true
  compressionEnabled: true
  includeInReports: true 